DATASET:
  NAME: 'voc'
  NUM_CLASSES: 20
  DATAROOT: 'data/VOCdevkit/VOC2012/'
  SCALE: [2048, 336]
  RATIO_RANGE: [0.5, 2.0]
  CROP_SIZE: [512, 512]
  CAT_MAX_RATIO: 0.75
  IMG_NORM_CFG:
    MEAN: [122.771, 116.746, 104.094]
    STD: [68.501, 66.632, 70.323]
    RGB: True
  TEXT_WEIGHT: 'text/voc_ViT16_clip_text.pth'
  REDUCE_ZERO_LABEL: TRUE

MODEL:
  FEATURE_EXTRACTOR: 'vit'
  TEXT_CHANNEL: 512
  VISUAL_CHANNEL: 768
  TRAINING: False
  CLASS_GATE:
    ENABLE: True
    THRESHOLD: 0.20
    TEMP: 10.0
    LOG_BIAS_SCALE: 2.0

TEST:
  BATCH_SIZE: 1
  PD: 1.0

EVAL_METRIC: "miou"
SAVE_DIR: "experiments/voc_classgate_s2/"
LOAD_PATH: "experiments/official/voc_reclippp_854/best_weight.pth"
NUM_WORKERS: 4
