DATASET:
  NAME: 'voc'
  NUM_CLASSES: 20
  DATAROOT: 'data/VOCdevkit/VOC2012/'
  SCALE: [2048, 336]
  RATIO_RANGE: [0.5, 2.0]
  CROP_SIZE: [336, 336]
  CAT_MAX_RATIO: 0.75
  IMG_NORM_CFG:
    MEAN: [122.771, 116.746, 104.094]
    STD: [68.501, 66.632, 70.323]
    RGB: True
  TEXT_WEIGHT: 'text/voc_ViT16_clip_text.pth'
  K: 2
  THRESHOLD: 23
  REDUCE_ZERO_LABEL: TRUE
  IGNORE_INDEX: 255

MODEL:
  FEATURE_EXTRACTOR: 'vit'
  TEXT_CHANNEL: 512
  VISUAL_CHANNEL: 768
  TRAINING: True
  PRESENCE:
    MODE: "zglobal"
    INIT_FROM: "experiments/official/voc_reclippp_854/best_weight.pth"
    BCE_W: 1.0
    NEG_POS_W: 0.2
    REG_W: 0.1

TRAIN:
  BATCH_SIZE: 1
  MAX_EPOCH: 50
  EPOCH: 50
  LR: 0.01

TEST:
  BATCH_SIZE: 1

EVAL_METRIC: "miou"
SAVE_DIR: "experiments/voc_presence/"
NUM_WORKERS: 4
